Comessa6/Comessa6/Controllers/HomeController.cs
using Comessa6.Models;
using Comessa6.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Comessa6.Controllers
{
  public class HomeController : Controller
  {
    private IComessaEntitiesFactory factory;

    public HomeController(IComessaEntitiesFactory factory)
    {
      this.factory = factory;
    }

    [Authorize]
    public ActionResult Index()
    {
      if (Session["UserID"] == null)
      {
        //System.Web.Security.FormsAuthentication.GetAuthCookie()
        return RedirectToAction("Login", "Authentication");
      }
      IndexViewModel indexVM = new IndexViewModel();
      #region Get Providers
      indexVM.Providers = new ProvidersViewModel();
      using (Comessa5Context repository = factory.GetContext())
      {
        var itemsInfo = repository.cprovider.OrderBy(provider => provider.priority);
        foreach (var providerInfo in itemsInfo)
        {
          ProviderViewModel providerVM = new ProviderViewModel { ID = providerInfo.id, Name = providerInfo.name, IsVisible = providerInfo.isVisible, TodaysDinner = (DateTime.Today.Year.Equals(providerInfo.dinnerLastModified.Year) && (DateTime.Today.DayOfYear.Equals(providerInfo.dinnerLastModified.DayOfYear))) ? providerInfo.dinnerText : null };
          indexVM.Providers.Providers.Add(providerVM);
        }
      }
        #endregion
      
      return View(indexVM);
    }

    public ActionResult About()
    {
      ViewBag.Message = "Your application description page.";

      return View();
    }

    public ActionResult Contact()
    {
      ViewBag.Message = "Your contact page.";

      return View();
    }
  }
}

Comessa6/Comessa6/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Comessa6.Models;
using Comessa6.ViewModels;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


namespace Comessa6.Controllers
{
  public class ItemsController : Controller
  {
    private IComessaEntitiesFactory factory;

    public ItemsController(IComessaEntitiesFactory factory)
    {
      this.factory = factory;
    }
    [HttpGet]
    public async Task<ActionResult> GetItems(int providerID)
    {
      using (Comessa5Context repository = factory.GetContext())
      {
        List<ItemViewModel> items = await (from citem item
                                 in repository.citem
                                           where item.providerId == providerID
                                           select new ItemViewModel
                                           {
                                             ID = item.id,
                                             Name = item.name,
                                             Price = item.price,
                                             Priority = item.priority
                                           }).ToListAsync();
        return PartialView("ItemsView", items.OrderBy(item => item.Priority));
      }
    }
  }
}

Comessa6/Comessa6/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Comessa6.ViewModels;
using System.Threading.Tasks;
using Comessa6.Models;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Comessa6.Controllers
{
  public class OrdersController : Controller
  {
    private IComessaEntitiesFactory factory;

    public OrdersController(IComessaEntitiesFactory factory)
    {
      this.factory = factory;
    }
    // GET: Orders
    [HttpGet]
    public async Task<ActionResult> GetOrders(int userID)
    {
      List<OrderViewModel> orders = null;
      #region Get todays orders
      if (userID == -1)
      {
        DateTime ordersOlderThan = DateTime.Now;
        ordersOlderThan -= TimeSpan.FromHours(ordersOlderThan.Hour);

        //int id = (int)Session["UserID"];
        using (Comessa5Context repository = factory.GetContext())
        {
          orders = await repository.corder.Include("citem").Include("citem.cprovider").Include("cuser")
          .Where(order => order.date > ordersOlderThan)
          .OrderByDescending(order => order.citem.cprovider.id)
          .Select(orderInfo => new OrderViewModel
          {
            ID = orderInfo.id,
            ItemName = orderInfo.citem.name,
            ItemID = (int)orderInfo.itemId,
            Price = orderInfo.price,
            Quantity = orderInfo.quantity,
            Comment = orderInfo.comment,
            ProviderName = orderInfo.citem.cprovider.name,
            Status = (OrderStatus)orderInfo.status,
            UserName = orderInfo.cuser.name,
            UserID = orderInfo.userId ?? -1,
            ForCurrentUserOnly = false
          }
          ).ToListAsync();
        }
      }
      #endregion
      #region get orders for current user
      else
      {
        using (Comessa5Context repository = factory.GetContext())
        {
          orders = await repository.corder.Include("citem").Include("citem.cprovider").Include("cuser")
         .Where(order => order.userId == userID)
         .OrderByDescending(order => order.id)
         .Select(orderInfo => new OrderViewModel
         {
           ID = orderInfo.id,
           ItemName = orderInfo.citem.name,
           ItemID = (int)orderInfo.itemId,
           Price = orderInfo.price,
           Quantity = orderInfo.quantity,
           Comment = orderInfo.comment,
           ProviderName = orderInfo.citem.cprovider.name,
           Status = (OrderStatus)orderInfo.status,
           UserName = orderInfo.cuser.name,
           UserID = orderInfo.userId ?? -1,
           ForCurrentUserOnly = true,
           Date = orderInfo.date
         }
         ).ToListAsync();
        }
      }
      #endregion
      return PartialView("OrdersView", orders);
    }

    [HttpGet]
    public ActionResult CreateOrder(int itemID)
    {
      return PartialView("CreateOrderView", new OrderViewModel { ItemID = itemID, Quantity = 1 });
    }

    [HttpGet]
    public ActionResult CreateOrderFromOrder(int itemID, string comment)
    {
      return PartialView("CreateOrderView", new OrderViewModel { ItemID = itemID, Quantity = 1, Comment = comment });
    }

    [HttpPost]
    public async Task<ActionResult> SaveOrder(int itemID, decimal quantity, string comments)
    {
      return await SaveOrder(itemID, (int)Session["UserID"], quantity, comments);
    }

    public async Task<ActionResult> SaveOrder(int itemID, int userID, decimal quantity, string comments)
    {
      //ToDo: check if it's possible to do that using 1 operation instead of 2 using EF
      //...or parse the whole citem as argument here
      using (Comessa5Context repository = factory.GetContext())
      {
        citem item = repository.citem.Where(citem => citem.id == itemID).FirstOrDefault();
        cuser server = repository.cuser.Where(cuser => cuser.isServer && !cuser.isMasterServer).FirstOrDefault();
        repository.corder.Add(new corder
        {
          itemId = itemID,
          quantity = quantity,
          comment = comments,
          userId = userID,
          itemName = item.name,
          price = item.price,
          date = DateTime.Now,
          status = (int)OrderStatus.Ordered,
          sellerId = server == null ? -1 : server.id
        });
        await repository.SaveChangesAsync();
      }
      return Json(true);
    }

    [HttpPost]
    public async Task<ActionResult> DeleteOrder(int ID)
    {
      using (Comessa5Context repository = factory.GetContext())
      {
        var toRemove = repository.corder.Where(order => order.id == ID).SingleOrDefault();
        if (toRemove == null) return Json(false);
        repository.corder.Remove(toRemove);
        await repository.SaveChangesAsync();
      }
      // Delete the item in the database
      return Json(true); // or if there is an error, return Json(null); to indicate failure
    }
  }
}

Comessa6/Comessa6/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Comessa6/Comessa6/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Comessa6/Comessa6/Views/Home/Index.cshtml
<!DOCTYPE html>
@{
    ViewBag.Title = "Comessa6";
}
@using Comessa6.ViewModels;
@model IndexViewModel
<script type="text/javascript" src="~/Scripts/ordering.js"></script>
<script type="text/javascript" src="~/Scripts/jquery-2.2.4.min.js"></script>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    @*<meta name="viewport" content="width=device-width, initial-scale=1">*@
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/favicon.ico">
    <title>Comessa6</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/Site.css" rel="stylesheet">
    <link href="~/Content/index.css" rel="stylesheet">
    <meta http-equiv="refresh" content="43200">
</head>
<div>
    <div class="col-lg-6">
        <div class="columnHeader">Zamów</div>
        <div class="panel-group provider" id="providers">
            <div class="panel">
                @{int i = 0; }
                @foreach (ProviderViewModel provider in Model.Providers.Providers)
                {
                    if (!provider.IsVisible)
                    {
                        continue;
                    }
                    i++;
                    <div class="provider-header" data-toggle="collapse" data-parent="#providers" href="#@("i" + i.ToString())" providerID="@provider.ID">@provider.Name</div>
                    <div class="provider-dinner">@provider.TodaysDinner</div>
                    <div id="@("i" + i.ToString())" class="panel-collapse collapse" style="font-size:small;">
                        <div id="@("provider" + provider.ID.ToString())"></div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div id="todaysOrdersHeader" class="columnHeaderSwitchable">Zamówione dziś</div>
        <div id="myOrdersHeader" class="columnHeaderSwitchable">Moje zamówienia</div>
        <div>
            <div id="currentOrders" />
        </div>
        <div>
            <div id="currentPayments" />
        </div>
    </div>
</div>
<script>
    var OrdersUserID = -1;
    $(function () {
        $(".provider-header").each(function () {
            var button = $(this);
            var providerID = button.attr("providerID");
            if (providerID)
            {
                button.click(function () {
                    var itemsPanel = $("#provider" + providerID);
                    if (itemsPanel.itemsLoaded)
                        return;
                    $.ajax({
                        url: '@Url.Action("GetItems", "Items")',
                        type: 'GET',
                        cache: false,
                        data: { providerID },
                        success: function (result) { itemsPanel.html(result); },
                        error: function (error) { alert("Database failure: " + error.statusText); }
                    });
                    itemsPanel.itemsLoaded = true;
                });
            }
        });
    });
    function loadOrders() {
        var link = '@Url.Action("GetOrders", "Orders")';
        link = link + "?userID=" + OrdersUserID;
        //link.replace("replace", "asfd");
        $("#currentOrders").load(link);
    };
    function loadPayments() {
        var link = '@Url.Action("GetPayments", "Payments")';
        link = link + "?userID=" + OrdersUserID;
        $("#currentPayments").load(link);
    };
    $(document).ready(function () {
        loadOrders();
        loadPayments();
        $('#myOrdersHeader').hide();
    });

    setInterval(function () {
        loadOrders();
    }, 60000);

    setInterval(function () {
        loadPayments();
    }, 60000);

    $("#todaysOrdersHeader").click(function () {
        $("#myOrdersHeader, #todaysOrdersHeader").toggle("slow", function () { });
        OrdersUserID = '@Session["UserID"]';
        loadOrders();
        loadPayments();
    });

    $("#myOrdersHeader").click(function () {
        $("#myOrdersHeader, #todaysOrdersHeader").toggle("slow", function () { });
        OrdersUserID = -1;
        loadOrders();
        loadPayments();
    });
</script>